version: '3'

services:
  db-postgres-evento:
    image: postgres:alpine
    ports:
      - "5432:5432"
    container_name: "db-postgres-evento"
    restart: always
    volumes:
      - ./database-evento:/var/lib/postgressql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

volumes:
  database-evento-api: